### ISSUE TITLE
Error in np.squeeze

### ISSUE THREAD

**Issue by lpsantao** [henrypowell87/NTURGB-D_Skeletons_Formatter#1]
In line 229 I get the following error:
"ValueError: cannot select an axis to squeeze out which has size not equal to one".
When printing the shape of loaded I get [nr of files, 1, 300, 600]. Am I doing something wrong?

**Comment by henrypowell87** [comment]
Hi there, I'm finding it difficult to reproduce this error. If I run the `preprocess_training()` function on the NTURGB+D sekeltons data over 1000 files with a `training_split_size` of 80 I get the following output in the console: 
```
Final training data dimensions: (800, 30, 75)
One-hot classes matrix:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Final training labels dimensions: (800, 30) 

```

So `loaded` is giving a tensor  with shape `[number of files, number of frames, number of features]` which is correct. From your description it looks like the second dimension of your tensor (`[...,1,...,...]`)shouldn't be there as the first dimension (`[nr of files,...,...,...]`)  is also giving the number of files. It's difficult for me guess where the error is coming from as I can't see all of your code. I've updated the code a bit since the last commit so I will commit the updated version with the hope that it will make the difference. 

Here are some things to keep in mind:

* Make sure you are using python version 3.X and have the up to date versions of the libraries you need for this code to work (numpy, pandas etc)

* If you're using this formatting as you currently have it to train a RNN or LSTM then you will need to significantly reduce the number of frames for each example (from 300 to about 30) other wise the network will not learn due to the large length of the time series.

* If you are training an LSTM your data will need to be of shape `[samples, time_steps, feaures]` so you will need to lose the second dimension of your tensor as you currently have it.

* Try to get the code working on a simpler version of the data and then build up from there to make debugging easier. For instances reduce the features of each sample to 3 (you can now do this by setting the `three_d` parameter of `process_raw_data()` to `True` and reduce the number of time steps in each sample from somewhere in the range [10, 30]. You may be getting the error above because numpy is trying to append arrays to parent array that have different dimensions in the second axis.

I hope this helps.

Henry

**Comment by henrypowell87** [comment]
If you are satified with this can you let me know so I can close this issue.

**Comment by lpsantao** [comment]
> If you are satified with this can you let me know so I can close this issue.

Yes, you can close it, thank you for the awesome work and explanation!
